### ISSUE TITLE
TZ env variable not setting timezone properly

### ISSUE THREAD

**Issue by billimek** [jacobalberty/unifi-docker#415]
### Host operating system

debian (docker)

### What tag are you using

`6.0.45`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

Kubernetes helm chart for unifi: https://github.com/k8s-at-home/charts/tree/master/charts/unifi

### What do you expect to happen?

setting `TZ` to a valid value be honored and timezone to be applied properly

### What actually happens?

Timezone is not being applied

This is the situation currently with `TZ` set to `America/New_York`:

```console
❯ k exec -ti unifi-5586bd94dd-xphpc -- bash
root@unifi-5586bd94dd-xphpc:/unifi# echo $TZ
America/New_York
root@unifi-5586bd94dd-xphpc:/unifi# date
Fri Feb  5 03:23:05 America 2021
root@unifi-5586bd94dd-xphpc:/unifi#
```

If package `tzdata` is installed in the container, this is the result instead:

```console
❯ k exec -ti unifi-5586bd94dd-xphpc -- bash
root@unifi-5586bd94dd-xphpc:/unifi# echo $TZ
America/New_York
root@unifi-5586bd94dd-xphpc:/unifi# date
Thu Feb  4 22:23:51 EST 2021
root@unifi-5586bd94dd-xphpc:/unifi#
```

**Comment by jacobalberty** [comment]
This was fixed with the merge of #416

**Comment by buckaroogeek** [comment]
Has this update been pushed to a release on docker hub? I pulled the latest version this moning (7 March) and still see UTC time stamps in the container and unifi logs. 

thanks
