### ISSUE TITLE
Backup functions from within controller failing. 

### ISSUE THREAD

**Issue by markdexter2** [jacobalberty/unifi-docker#417]
Ubuntu 18.04 (on Azure).

Defaults as given on the site

### What do you expect to happen?
Backups from with in the controller to work

### What actually happens?

Backups fail with an error message of "There was an error generating a new backup file."

logging on debug reveals [2021-02-17T04:26:52,615] <backup> ERROR system - zipDir error
java.io.FileNotFoundException: /usr/lib/unifi/data/backup/6.0.45.unf (Permission denied)

I assume I've done somethin odd, but I'm just using the docker-compose.yml as given and everything else works fine.  Has anyone else seen anything similar ?

**Comment by victorgrigoroiu** [comment]
Hi @markdexter2. Hope you are well.

I have the same Issue with my container.

I have only a temporary solution to offer:

- log into your docker container with `sudo docker exec -u root -it <container_id> /bin/bash`
- got to the backup folder with `cd /usr/lib/unifi/data`
- change the owner an the group of the backup folder with `chmod -R unifi:unifi ./backup`

You should then be able to create a backup file.

In my case is for some reason the owner and the group of backup folder `root:root`. Dont't realy know how to fix it in the long term.

Hope this helps.

**Comment by markdexter2** [comment]
yep that worked, will do for a work around for now, thanks heaps.

**Comment by rickyzhang82** [comment]
You mean `chown`

**Comment by rickyzhang82** [comment]
Should we fix volume mount instead?

```
 22     volumes:
 23       - dir:/unifi
 24       - data:/unifi/data
 25       - log:/unifi/log
 26       - cert:/unifi/cert
 27       - init:/unifi/init.d
 28       - run:/var/run/unifi
 29       # Mount local folder for backups and autobackups
 30       - ./backup:/unifi/data/backup
```

**Comment by 40417256** [comment]
I fixed it in the docker (also takes care of autobackup) file like that

#RUN mkdir -p /unifi && chown unifi:unifi -R /unifi
# fix the backup and **autobackup** known error
RUN mkdir -p /unifi/backup/autobackup && chown unifi:unifi -R /unifi

**Comment by HansTo** [comment]
Aug 15, problem still exists:. Fresh install on fresh server using the docker-compose.yaml.


```
root@XXXXXXXXXXXc:/usr/lib/unifi/data# ls -al
total 124
drwxr-xr-x 5 unifi unifi  4096 Aug 15 18:45 .
drwxr-xr-x 6 unifi unifi  4096 Aug 15 18:25 ..
drwxr-xr-x 2  1000  1000  4096 Aug 10 22:01 backup
drwxr-xr-x 2 unifi unifi  4096 Aug 15 18:25 db
-rw-r--r-- 1 unifi unifi 17551 Aug 15 18:31 firmware.json
-rw-r--r-- 1 unifi unifi  2248 Aug 15 18:25 keystore
-rw-r--r-- 1 unifi unifi  1424 Aug 15 18:30 model_lifecycles.json
-rw-r--r-- 1 unifi unifi 65264 Aug 16 02:15 request_metrics.csv
drwxr-xr-x 3 unifi unifi  4096 Aug 15 20:32 sites
-rw-r--r-- 1 unifi unifi  1461 Aug 15 18:30 system.properties
-rw-r--r-- 1 unifi unifi  1461 Aug 15 18:30 system.properties.bk
```

i chown;ed backup to unifi:unifi and chmod 777 too. 

Still getting backup errors
[unif_error_log.txt](https://github.com/jacobalberty/unifi-docker/files/6989399/unif_error_log.txt)

**Comment by alex4108** [comment]
> 
> 
> Aug 15, problem still exists:. Fresh install on fresh server using the docker-compose.yaml.
> 
> ```
> root@XXXXXXXXXXXc:/usr/lib/unifi/data# ls -al
> total 124
> drwxr-xr-x 5 unifi unifi  4096 Aug 15 18:45 .
> drwxr-xr-x 6 unifi unifi  4096 Aug 15 18:25 ..
> drwxr-xr-x 2  1000  1000  4096 Aug 10 22:01 backup
> drwxr-xr-x 2 unifi unifi  4096 Aug 15 18:25 db
> -rw-r--r-- 1 unifi unifi 17551 Aug 15 18:31 firmware.json
> -rw-r--r-- 1 unifi unifi  2248 Aug 15 18:25 keystore
> -rw-r--r-- 1 unifi unifi  1424 Aug 15 18:30 model_lifecycles.json
> -rw-r--r-- 1 unifi unifi 65264 Aug 16 02:15 request_metrics.csv
> drwxr-xr-x 3 unifi unifi  4096 Aug 15 20:32 sites
> -rw-r--r-- 1 unifi unifi  1461 Aug 15 18:30 system.properties
> -rw-r--r-- 1 unifi unifi  1461 Aug 15 18:30 system.properties.bk
> ```
> 
> i chown;ed backup to unifi:unifi and chmod 777 too.
> 
> Still getting backup errors
> [unif_error_log.txt](https://github.com/jacobalberty/unifi-docker/files/6989399/unif_error_log.txt)

Can you show `ls -al` from your host, as well as the states before and after running the `chmod` command on your host?  `chmod -R 777 ./backup` worked for me today, when I noticed my controller wasn't backing up!
