### ISSUE TITLE
latest image breaks previous latest

### ISSUE THREAD

**Issue by valentt** [jacobalberty/unifi-docker#445]
I have a watchtower docker that automatically pulls in the latest Docker Unifi image from your repository, and that has worked without issues for the last 24 months. But the latest image you released 3-4 days ago breaks. After starting the image I don't see my Unifi dashboard but I only get a message saying "Can't upgrade from version.... "

**Comment by valentt** [comment]
Latest know working Unifi image has image id "4e673a2b55dc" and has been created 13 days ago.

**Comment by mariozelaschi** [comment]
true, i can confirm that:
UniFi Controller startup failed
We do not support upgrading from 6.2.23.

**Comment by brbeaird** [comment]
Same issue here. It looks like the repo jumped from 6.1.71 to 6.2.23. I don't think Unifi allows that jump. I'm in the process of trying to force my docker container to the 6.2.17-rc tag and then to the 6.2.23 latest tag.

**Comment by brbeaird** [comment]
Ok, I'm back up and running after this:

1. Restarted the container, having it explicitly pull from jacobalberty/unifi:6.2.17-rc
2. Restarted the container again, having it explicitly pull from jacobalberty/unifi:6.2.23

Although after reading through the docs, it seems like the issue may be that the "latest" tag is still pointing to 6.1.7. I am wondering now if at some point "latest" was pointed at a 6.2 version long enough for some of us to actually do that upgrade, but then it was backed down to 6.1.x, and our systems blew up trying to downgrade. The fix in that case is probably just to bypass "latest" and point straight to 6.2.23.

**Comment by dennypage** [comment]
Look at the prior 4-5 prior (closed) issues.

**Comment by vrillusions** [comment]
> Although after reading through the docs, it seems like the issue may be that the "latest" tag is still pointing to 6.1.7. I am wondering now if at some point "latest" was pointed at a 6.2 version long enough for some of us to actually do that upgrade, but then it was backed down to 6.1.x, and our systems blew up trying to downgrade. The fix in that case is probably just to bypass "latest" and point straight to 6.2.23.

Yep that's what happened.  5 days ago commit 52f6fb4 reverted it from 6.2.23 back to 6.1.71.  And you can't go back versions unless you have a backup from that version to restore to.  I was on `jacobalberty/unifi:stable-6` and switched it to `jacobalberty/unifi:6.2.23` and it's back up.

**Comment by brbeaird** [comment]
> Look at the prior 4-5 prior (closed) issues.

Oops, yeah I missed that, too. Honestly, it's probably worth leaving one of these open for awhile so people will stop opening new ones.

**Comment by jacobalberty** [comment]
The 6.2.23 upgrade broke for many people so Ubiquiti pulled it down.  on this github we had issues opened about the 6.2.23 upgrade breaking as well. So when Ubiquiti reverted 6.2.23 back to 6.1.17 I did the same with this repo. The solution for now is to use the `jacobalberty/unifi:6.2` tag if you were upgraded to 6.2.23. I left that in tact. Unfortunately shortly after I tell people this they close the issue and then a few hours later someone else comes and opens a new one.

There's a 6.2.25 in RC status on the release page now but I would have expected UI to tag it stable by now and they haven't yet.

**Comment by jacobalberty** [comment]
This should now be fixed. 6.2.25 was just pushed to the hub

**Comment by foorschtbar** [comment]
Sry, but I still do not understand how to upgrade to 6.1x or 6.2.x.

I am on 6.0.45 and if I set the tag to
- last
- stable-6 or
- 6.2.17-rc
the container cannot be started. 

What am I doing wrong? The readme had no update/upgrade part, that means for me change the container tag (or latest) should work?
